### ISSUE TITLE
Logs show missing forge

### ISSUE THREAD

**Issue by AlexFigas** [scorewinner/atm-docker#1]
The Forge version I've specified is the one outlined in the manifest.json, namely forge-1.20.1-47.2.17-installer.jar. Do I need to download it and place it in the /data directory?

**Comment by AlexFigas** [comment]
For further notice yes,  it is necessary to download the JAR file specified in the manifest.json, update the docker-compose accordingly, and place the JAR file in the /data directory.

**Comment by AlexFigas** [comment]
Can't make the server to get modded. It always start's as vanilla 1.21.1

**Comment by scorewinner** [comment]
> Can't make the server to get modded. It always start's as vanilla 1.21.1

Did you Download the Server Files from Curseforge? The forge file is included in the downloaded files. Just copy the filename and add it to the docker compose file.
In addition, the environment should be `TYPE: FORGE`.
And just to be sure, are the permissions of all the files set to the correct user.
